# Generated by Django 6.1.1 on 2026-09-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('survey', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('transcript', models.JSONField(default=list)),
                ('match', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
