# Generated by Django 6.1.1 on 2026-09-10 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='exchanges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='fee',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('ongoing', 'Ongoing'), ('review', 'In firm review'), ('closed', 'Closed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='case',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
