# Generated by Django 6.1.1 on 2026-09-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_case_assigned_to_case_exchanges_case_fee_case_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
